export const roles = [
    { value: "patient", label: "Patient" },
    { value: "doctor", label: "Doctor" }
]

export const symptoms = [
    { value: 'itching', label: 'Itching' },
    { value: 'skin_rash', label: 'Skin Rash' },
    { value: 'nodal_skin_eruptions', label: 'Nodal Skin Eruptions' },
    { value: 'continuous_sneezing', label: 'Continuous Sneezing' },
    { value: 'shivering', label: 'Shivering' },
    { value: 'chills', label: 'Chills' },
    { value: 'joint_pain', label: 'Joint Pain' },
    { value: 'stomach_pain', label: 'Stomach Pain' },
    { value: 'acidity', label: 'Acidity' },
    { value: 'ulcers_on_tongue', label: 'Ulcers On Tongue' },
    { value: 'muscle_wasting', label: 'Muscle Wasting' },
    { value: 'vomiting', label: 'Vomiting' },
    { value: 'burning_micturition', label: 'Burning Micturition' },
    { value: 'spotting_ urination', label: 'Spotting  Urination' },
    { value: 'fatigue', label: 'Fatigue' },
    { value: 'weight_gain', label: 'Weight Gain' },
    { value: 'anxiety', label: 'Anxiety' },
    { value: 'cold_hands_and_feets', label: 'Cold Hands And Feets' },
    { value: 'mood_swings', label: 'Mood Swings' },
    { value: 'weight_loss', label: 'Weight Loss' },
    { value: 'restlessness', label: 'Restlessness' },
    { value: 'lethargy', label: 'Lethargy' },
    { value: 'patches_in_throat', label: 'Patches In Throat' },
    { value: 'irregular_sugar_level', label: 'Irregular Sugar Level' },
    { value: 'cough', label: 'Cough' },
    { value: 'high_fever', label: 'High Fever' },
    { value: 'sunken_eyes', label: 'Sunken Eyes' },
    { value: 'breathlessness', label: 'Breathlessness' },
    { value: 'sweating', label: 'Sweating' },
    { value: 'dehydration', label: 'Dehydration' },
    { value: 'indigestion', label: 'Indigestion' },
    { value: 'headache', label: 'Headache' },
    { value: 'yellowish_skin', label: 'Yellowish Skin' },
    { value: 'dark_urine', label: 'Dark Urine' },
    { value: 'nausea', label: 'Nausea' },
    { value: 'loss_of_appetite', label: 'Loss Of Appetite' },
    { value: 'pain_behind_the_eyes', label: 'Pain Behind The Eyes' },
    { value: 'back_pain', label: 'Back Pain' },
    { value: 'constipation', label: 'Constipation' },
    { value: 'abdominal_pain', label: 'Abdominal Pain' },
    { value: 'diarrhoea', label: 'Diarrhoea' },
    { value: 'mild_fever', label: 'Mild Fever' },
    { value: 'yellow_urine', label: 'Yellow Urine' },
    { value: 'yellowing_of_eyes', label: 'Yellowing Of Eyes' },
    { value: 'acute_liver_failure', label: 'Acute Liver Failure' },
    { value: 'fluid_overload', label: 'Fluid Overload' },
    { value: 'swelling_of_stomach', label: 'Swelling Of Stomach' },
    { value: 'swelled_lymph_nodes', label: 'Swelled Lymph Nodes' },
    { value: 'malaise', label: 'Malaise' },
    { value: 'blurred_and_distorted_vision', label: 'Blurred And Distorted Vision' },
    { value: 'phlegm', label: 'Phlegm' },
    { value: 'throat_irritation', label: 'Throat Irritation' },
    { value: 'redness_of_eyes', label: 'Redness Of Eyes' },
    { value: 'sinus_pressure', label: 'Sinus Pressure' },
    { value: 'runny_nose', label: 'Runny Nose' },
    { value: 'congestion', label: 'Congestion' },
    { value: 'chest_pain', label: 'Chest Pain' },
    { value: 'weakness_in_limbs', label: 'Weakness In Limbs' },
    { value: 'fast_heart_rate', label: 'Fast Heart Rate' },
    { value: 'pain_during_bowel_movements', label: 'Pain During Bowel Movements' },
    { value: 'pain_in_anal_region', label: 'Pain In Anal Region' },
    { value: 'bloody_stool', label: 'Bloody Stool' },
    { value: 'irritation_in_anus', label: 'Irritation In Anus' },
    { value: 'neck_pain', label: 'Neck Pain' },
    { value: 'dizziness', label: 'Dizziness' },
    { value: 'cramps', label: 'Cramps' },
    { value: 'bruising', label: 'Bruising' },
    { value: 'obesity', label: 'Obesity' },
    { value: 'swollen_legs', label: 'Swollen Legs' },
    { value: 'swollen_blood_vessels', label: 'Swollen Blood Vessels' },
    { value: 'puffy_face_and_eyes', label: 'Puffy Face And Eyes' },
    { value: 'enlarged_thyroid', label: 'Enlarged Thyroid' },
    { value: 'brittle_nails', label: 'Brittle Nails' },
    { value: 'swollen_extremeties', label: 'Swollen Extremeties' },
    { value: 'excessive_hunger', label: 'Excessive Hunger' },
    { value: 'extra_marital_contacts', label: 'Extra Marital Contacts' },
    { value: 'drying_and_tingling_lips', label: 'Drying And Tingling Lips' },
    { value: 'slurred_speech', label: 'Slurred Speech' },
    { value: 'knee_pain', label: 'Knee Pain' },
    { value: 'hip_joint_pain', label: 'Hip Joint Pain' },
    { value: 'muscle_weakness', label: 'Muscle Weakness' },
    { value: 'stiff_neck', label: 'Stiff Neck' },
    { value: 'swelling_joints', label: 'Swelling Joints' },
    { value: 'movement_stiffness', label: 'Movement Stiffness' },
    { value: 'spinning_movements', label: 'Spinning Movements' },
    { value: 'loss_of_balance', label: 'Loss Of Balance' },
    { value: 'unsteadiness', label: 'Unsteadiness' },
    { value: 'weakness_of_one_body_side', label: 'Weakness Of One Body Side' },
    { value: 'loss_of_smell', label: 'Loss Of Smell' },
    { value: 'bladder_discomfort', label: 'Bladder Discomfort' },
    { value: 'foul_smell_of urine', label: 'Foul Smell Of Urine' },
    { value: 'continuous_feel_of_urine', label: 'Continuous Feel Of Urine' },
    { value: 'passage_of_gases', label: 'Passage Of Gases' },
    { value: 'internal_itching', label: 'Internal Itching' },
    { value: 'toxic_look_(typhos)', label: 'Toxic Look (Typhos)' },
    { value: 'depression', label: 'Depression' },
    { value: 'irritability', label: 'Irritability' },
    { value: 'muscle_pain', label: 'Muscle Pain' },
    { value: 'altered_sensorium', label: 'Altered Sensorium' },
    { value: 'red_spots_over_body', label: 'Red Spots Over Body' },
    { value: 'belly_pain', label: 'Belly Pain' },
    { value: 'abnormal_menstruation', label: 'Abnormal Menstruation' },
    { value: 'dischromic _patches', label: 'Dischromic  Patches' },
    { value: 'watering_from_eyes', label: 'Watering From Eyes' },
    { value: 'increased_appetite', label: 'Increased Appetite' },
    { value: 'polyuria', label: 'Polyuria' },
    { value: 'family_history', label: 'Family History' },
    { value: 'mucoid_sputum', label: 'Mucoid Sputum' },
    { value: 'rusty_sputum', label: 'Rusty Sputum' },
    { value: 'lack_of_concentration', label: 'Lack Of Concentration' },
    { value: 'visual_disturbances', label: 'Visual Disturbances' },
    { value: 'receiving_blood_transfusion', label: 'Receiving Blood Transfusion' },
    { value: 'receiving_unsterile_injections', label: 'Receiving Unsterile Injections' },
    { value: 'coma', label: 'Coma' },
    { value: 'stomach_bleeding', label: 'Stomach Bleeding' },
    { value: 'distention_of_abdomen', label: 'Distention Of Abdomen' },
    { value: 'history_of_alcohol_consumption', label: 'History Of Alcohol Consumption' },
    { value: 'fluid_overload.1', label: 'Fluid Overload.1' },
    { value: 'blood_in_sputum', label: 'Blood In Sputum' },
    { value: 'prominent_veins_on_calf', label: 'Prominent Veins On Calf' },
    { value: 'palpitations', label: 'Palpitations' },
    { value: 'painful_walking', label: 'Painful Walking' },
    { value: 'pus_filled_pimples', label: 'Pus Filled Pimples' },
    { value: 'blackheads', label: 'Blackheads' },
    { value: 'scurring', label: 'Scurring' },
    { value: 'skin_peeling', label: 'Skin Peeling' },
    { value: 'silver_like_dusting', label: 'Silver Like Dusting' },
    { value: 'small_dents_in_nails', label: 'Small Dents In Nails' },
    { value: 'inflammatory_nails', label: 'Inflammatory Nails' },
    { value: 'blister', label: 'Blister' },
    { value: 'red_sore_around_nose', label: 'Red Sore Around Nose' },
    { value: 'yellow_crust_ooze', label: 'Yellow Crust Ooze' }
]


export const initialSymptomState = {
    "itching": false,
    "skin_rash": false,
    "nodal_skin_eruptions": false,
    "continuous_sneezing": false,
    "shivering": false,
    "chills": false,
    "joint_pain": false,
    "stomach_pain": false,
    "acidity": false,
    "ulcers_on_tongue": false,
    "muscle_wasting": false,
    "vomiting": false,
    "burning_micturition": false,
    "spotting_ urination": false,
    "fatigue": false,
    "weight_gain": false,
    "anxiety": false,
    "cold_hands_and_feets": false,
    "mood_swings": false,
    "weight_loss": false,
    "restlessness": false,
    "lethargy": false,
    "patches_in_throat": false,
    "irregular_sugar_level": false,
    "cough": false,
    "high_fever": false,
    "sunken_eyes": false,
    "breathlessness": false,
    "sweating": false,
    "dehydration": false,
    "indigestion": false,
    "headache": false,
    "yellowish_skin": false,
    "dark_urine": false,
    "nausea": false,
    "loss_of_appetite": false,
    "pain_behind_the_eyes": false,
    "back_pain": false,
    "constipation": false,
    "abdominal_pain": false,
    "diarrhoea": false,
    "mild_fever": false,
    "yellow_urine": false,
    "yellowing_of_eyes": false,
    "acute_liver_failure": false,
    "fluid_overload": false,
    "swelling_of_stomach": false,
    "swelled_lymph_nodes": false,
    "malaise": false,
    "blurred_and_distorted_vision": false,
    "phlegm": false,
    "throat_irritation": false,
    "redness_of_eyes": false,
    "sinus_pressure": false,
    "runny_nose": false,
    "congestion": false,
    "chest_pain": false,
    "weakness_in_limbs": false,
    "fast_heart_rate": false,
    "pain_during_bowel_movements": false,
    "pain_in_anal_region": false,
    "bloody_stool": false,
    "irritation_in_anus": false,
    "neck_pain": false,
    "dizziness": false,
    "cramps": false,
    "bruising": false,
    "obesity": false,
    "swollen_legs": false,
    "swollen_blood_vessels": false,
    "puffy_face_and_eyes": false,
    "enlarged_thyroid": false,
    "brittle_nails": false,
    "swollen_extremeties": false,
    "excessive_hunger": false,
    "extra_marital_contacts": false,
    "drying_and_tingling_lips": false,
    "slurred_speech": false,
    "knee_pain": false,
    "hip_joint_pain": false,
    "muscle_weakness": false,
    "stiff_neck": false,
    "swelling_joints": false,
    "movement_stiffness": false,
    "spinning_movements": false,
    "loss_of_balance": false,
    "unsteadiness": false,
    "weakness_of_one_body_side": false,
    "loss_of_smell": false,
    "bladder_discomfort": false,
    "foul_smell_of urine": false,
    "continuous_feel_of_urine": false,
    "passage_of_gases": false,
    "internal_itching": false,
    "toxic_look_(typhos)": false,
    "depression": false,
    "irritability": false,
    "muscle_pain": false,
    "altered_sensorium": false,
    "red_spots_over_body": false,
    "belly_pain": false,
    "abnormal_menstruation": false,
    "dischromic _patches": false,
    "watering_from_eyes": false,
    "increased_appetite": false,
    "polyuria": false,
    "family_history": false,
    "mucoid_sputum": false,
    "rusty_sputum": false,
    "lack_of_concentration": false,
    "visual_disturbances": false,
    "receiving_blood_transfusion": false,
    "receiving_unsterile_injections": false,
    "coma": false,
    "stomach_bleeding": false,
    "distention_of_abdomen": false,
    "history_of_alcohol_consumption": false,
    "fluid_overload.1": false,
    "blood_in_sputum": false,
    "prominent_veins_on_calf": false,
    "palpitations": false,
    "painful_walking": false,
    "pus_filled_pimples": false,
    "blackheads": false,
    "scurring": false,
    "skin_peeling": false,
    "silver_like_dusting": false,
    "small_dents_in_nails": false,
    "inflammatory_nails": false,
    "blister": false,
    "red_sore_around_nose": false,
    "yellow_crust_ooze": false
}
